--- #YAML:1.0
name: version-Limit
version: 0.02
author:
  - John Peacock, E<lt>jpeacock@cpan.orgE<gt>
abstract: |-
  Perl extension for fine control of permitted versions
license: perl
requires:
  perl: 5.8.1
  version: 0.41
provides:
  version::Limit:
    file: lib/version/Limit.pm
    version: 0.02
generated_by: Module::Build version 0.24
